# Generated by Django 4.0.4 on 2022-05-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='Author_Table',
        ),
    ]
