# Generated by Django 4.0.4 on 2022-05-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
